table ⠀Measures
	lineageTag: 0cfc7a7d-e99a-43f5-b36c-1f5df695362c

	measure 'Official Title Count' =
			
			CALCULATE(
			    COUNTROWS(
			            VALUES(Study[Study Official Title])
			            ),
			            TREATAS(
			                VALUES('Clinical trial'[Study Key]),
			                Study[Study Key]
			            )
			        )
		formatString: #,0
		lineageTag: e78aeb25-7984-41c7-aff5-3f5935bb5a47

		changedProperty = Name

	measure 'Short Title Count v1' =
			
			CALCULATE(
			    DISTINCTCOUNT(Study[Study Short Title]),
			    CROSSFILTER('Clinical trial'[Study Key],Study[Study Key],Both)
			)
		formatString: #,0
		lineageTag: cfb50b8a-7881-41e3-a1b3-2365985277fc

		changedProperty = Name

	measure 'Short Title Count v2' =
			
			CALCULATE(
			    COUNTROWS(
			            VALUES(Study[Study Short Title])
			            ),
			            TREATAS(
			                VALUES('Clinical trial'[Study Key]),
			                Study[Study Key]
			            )
			        )
		formatString: #,0
		lineageTag: 8c106375-2ced-4fac-9b71-3622be8f17eb

		changedProperty = Name

	measure 'Organization Class Count' =
			
			CALCULATE(
			    COUNTROWS(
			            VALUES(Organization[Organization Class])
			            ),
			            TREATAS(
			                VALUES('Clinical trial'[Organization Key]),
			                Organization[Organization Key]
			            )
			        )
		formatString: #,0
		lineageTag: debc5143-b0c3-4173-99a8-2c07ef46c6b8

		changedProperty = Name

	measure 'Organization Full Name Count' =
			
			CALCULATE(
			    COUNTROWS(
			            VALUES(Organization[Organization Full Name])
			            ),
			            TREATAS(
			                VALUES('Clinical trial'[Organization Key]),
			                Organization[Organization Key]
			            )
			        )
		formatString: #,0
		lineageTag: 2f536dd2-ee8b-45da-83c2-e6361be7b496

		changedProperty = Name

	measure 'Organization Responsible Party Count' =
			
			CALCULATE(
			    COUNTROWS(
			            VALUES(Organization[Responsible Party])
			            ),
			            TREATAS(
			                VALUES('Clinical trial'[Organization Key]),
			                Organization[Organization Key]
			            )
			        )
		formatString: #,0
		lineageTag: 56ca152c-5d3f-44ea-927d-f69ad90ae072

		changedProperty = Name

	measure 'Intervention Name Count' =
			
			CALCULATE(
			            DISTINCTCOUNT(Intervention[Intervention Name]),
			            TREATAS(
			                VALUES('Clinical trial'[Intervention Key]),
			                Intervention[Intervention Key]
			            )
			        )
		formatString: #,0
		lineageTag: db540d59-fcc2-4aea-9c60-30e2d68c43f9

		changedProperty = Name

	measure 'Intervention Description Count' =
			
			CALCULATE(
			            DISTINCTCOUNT(Intervention[Intervention Description]),
			            TREATAS(
			                VALUES('Clinical trial'[Intervention Key]),
			                Intervention[Intervention Key]
			            )
			        )
		formatString: #,0
		lineageTag: 1d7c14bd-ee68-4e94-aedd-2ca198892428

		changedProperty = Name

	measure 'Condition Name Count' = ```
			
			CALCULATE(
			            DISTINCTCOUNT('Condition'[Condition Name]),
			            TREATAS(
			                VALUES('Clinical trial'[Condition Key]), 
			                'Condition'[Condition Key])
			        )
			```
		formatString: #,0
		lineageTag: 6589fe2c-f558-4095-a5db-47d1920f38fe

		changedProperty = Name

	measure 'Medical Subject Headings Name Count' = ```
			
			CALCULATE(
			            DISTINCTCOUNT('Condition'[Medical Subject Headings]),
			            TREATAS(
			                VALUES('Clinical trial'[Condition Key]), 
			                'Condition'[Condition Key])
			        )
			```
		formatString: #,0
		lineageTag: 59847407-46a9-4961-bcda-612de998f88e

		changedProperty = Name

	measure 'Number of trials' = COUNTROWS('Clinical trial')
		formatString: #,0
		lineageTag: 551a35e3-9b44-4110-b8c7-433fb0f0259f

		changedProperty = Name

		changedProperty = FormatString

	measure 'Outcome Measure Count' = DISTINCTCOUNT('Clinical trial'[Outcome Measure])
		formatString: #,0
		lineageTag: b0952ce2-d755-419d-b3b5-9a1237ec19ac

		changedProperty = Name

	measure 'Overall Status Count' = DISTINCTCOUNT('Clinical trial'[Overall Status])
		formatString: #,0
		lineageTag: a6f0a1a5-f8dc-4ac5-b02e-56e3376770f3

		changedProperty = Name

	measure 'Phases Count' = DISTINCTCOUNT('Clinical trial'[Phases])
		formatString: #,0
		lineageTag: 9bb881af-a4db-4b56-8a77-79170799afb1

		changedProperty = Name

	measure 'Primary Purpose Count' = DISTINCTCOUNT('Clinical trial'[Primary Purpose])
		formatString: #,0
		lineageTag: d8ab081a-c93b-4531-abfc-fea4204d2e4c

		changedProperty = Name

	measure 'Study Type Count' = DISTINCTCOUNT('Clinical trial'[Study Type])
		formatString: #,0
		lineageTag: 52c0180b-c4e1-4a3b-935c-508ca29220e1

		changedProperty = Name

	measure 'Standard Age Count' = DISTINCTCOUNT('Clinical trial'[Standard Age])
		formatString: #,0
		lineageTag: 31d00035-2ac9-4b08-8108-218446080390

	partition ⠀Measures = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				  #"Removed Columns" = Table.RemoveColumns(Source, {"Column1"})
				in
				  #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

